/**
 * @fileoverview Request handler routes.
 */

import { serveR2, _hashIndexes, r2Get } from '../core/r2.js';
import { isHex64 } from '../core/utils.js';
import { H_CACHED, H_IMMUTABLE, EMPTY_GZ, EMPTY_GZ_HASH, EMPTY_HASH } from '../core/constants.js';
import { getCacheStats } from '../core/cache.js';

/**
 * Handles explicit requests for static repository assets assigned to the path execution root.
 * Generates synthetic caching headers directly for config payloads avoiding heavy R2 fetches.
 *
 * @param {string} rawPath - The requested relative path string.
 * @param {Object} env - The Cloudflare environment bindings.
 * @param {Request} request - The inbound HTTP request.
 * @param {string} CONFIG_JSON_STRING - The JSON configuration string.
 * @returns {Promise<Response>} The HTTP Response object.
 */
export async function handleStaticAssets(rawPath, env, request, CONFIG_JSON_STRING) {
  if (rawPath === "robots.txt") {
    const hr = new Headers(H_CACHED);
    hr.set("Content-Type", "text/plain; charset=utf-8");
    hr.set("X-Debthin", "hit-synthetic");
    hr.set("X-Cache", "HIT");
    hr.set("X-Cache-Hits", "0");
    return new Response("User-agent: *\nAllow: /$\nDisallow: /\n", { headers: hr });
  }
  if (rawPath === "config.json") {
    const hc = new Headers(H_CACHED);
    hc.set("Content-Type", "application/json; charset=utf-8");
    hc.set("X-Debthin", "hit-synthetic");
    hc.set("X-Cache", "HIT");
    hc.set("X-Cache-Hits", "0");
    return new Response(CONFIG_JSON_STRING, { headers: hc });
  }
  if (rawPath === "health") {
    let r2 = "OK";
    try { await env.DEBTHIN_BUCKET.head("healthcheck-ping"); } catch (e) { r2 = "ERROR"; }
    const stats = { 
      status: r2 === "OK" ? "OK" : "DEGRADED", 
      r2, 
      cache: { ...getCacheStats(), distributions: _hashIndexes.size }, 
      time: Date.now() 
    };
    const hh = new Headers({ "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store", "X-Debthin": "hit-synthetic" });
    return new Response(JSON.stringify(stats, null, 2) + "\n", { headers: hh, status: r2 === "OK" ? 200 : 503 });
  }
  return serveR2(env, request, rawPath === "" ? "index.html" : rawPath);
}

/**
 * Issues an HTTP 301 redirect for requests targeting the /pool/ directory.
 * Instructs the apt client to fetch the binary directly from the upstream mirror, avoiding Cloudflare egress costs.
 *
 * @param {string} protocol - The request protocol (http or https).
 * @param {string} upstream - The target mirror hostname.
 * @param {string} rest - The object path segment after /pool/.
 * @returns {Response} The HTTP 301 redirect response.
 */
export function handleUpstreamRedirect(protocol, upstream, rest) {
  return new Response(null, {
    status: 301,
    headers: { "Location": `${protocol}://${upstream}/${rest}` }
  });
}

/**
 * Resolves content by inspecting the by-hash-index files generated by the ingest script.
 * Maintains a lazily-loaded reference map of hashes to relative file paths.
 * Intercepts calls for empty files and serves them exclusively from memory to bypass R2 charges.
 *
 * @param {Request} request - The inbound HTTP request.
 * @param {Object} env - The Cloudflare environment bindings.
 * @param {Object} ctx - The worker execution context.
 * @param {string} distro - The Linux distribution name.
 * @param {string} sha256 - The requested SHA256 file hash.
 * @returns {Promise<Response|null>} The resolved file content or null.
 */
export async function handleByHash(request, env, ctx, distro, sha256) {
  if (sha256 === EMPTY_GZ_HASH) {
    const heg = new Headers(H_IMMUTABLE);
    heg.set("Content-Type", "application/x-gzip");
    return new Response(request.method === "HEAD" ? null : EMPTY_GZ, { headers: heg });
  }
  if (sha256 === EMPTY_HASH) {
    const hep = new Headers(H_IMMUTABLE);
    hep.set("Content-Type", "text/plain; charset=utf-8");
    return new Response("", { headers: hep });
  }

  if (sha256.length === 64 && isHex64(sha256)) {
    let distroIndex = _hashIndexes.get(distro);

    if (!distroIndex || distroIndex instanceof Promise) {
      if (!distroIndex) {
        const promise = r2Get(env, `dists/${distro}/by-hash-index.json`, ctx).then(async obj => {
          const json = obj ? JSON.parse(await obj.text()) : {};
          const current = _hashIndexes.get(distro);
          const freshData = (current instanceof Promise || !current) ? {} : current;
          return Object.assign(json, freshData);
        }).catch(() => ({}));
        _hashIndexes.set(distro, promise);
        distroIndex = promise;
      }
      distroIndex = await distroIndex;
      _hashIndexes.set(distro, distroIndex);
    }

    const relPath = distroIndex[sha256];
    if (relPath) return serveR2(env, request, `dists/${distro}/${relPath}`, { immutable: true });
    return new Response("Not found\n", { status: 404 });
  }

  return null;
}

/**
 * Core dispatch engine for distribution-level files.
 * Re-maps paths for legacy aliases, strips PGP signatures from InRelease files when Release is requested,
 * and automatically decompresses Packages.gz payload streams internally when uncompressed Packages are requested.
 *
 * @param {Request} request - The inbound HTTP request.
 * @param {Object} env - The Cloudflare environment bindings.
 * @param {Object} ctx - The worker execution context.
 * @param {string} distro - The Linux distribution name.
 * @param {string} suitePath - The remaining path fragments.
 * @param {Object} tokens - Zero-allocation parsed path parts.
 * @param {Object} distroConfig - Distribution parameters from config.json.
 * @returns {Promise<Response|null>} Processed HTTP Response or null fallback.
 */
export async function handleDistributionHashIndex(request, env, ctx, distro, suitePath, { p1, p2, p3, p4 }, distroConfig) {
  const r2Key = `dists/${distro}/${suitePath.slice(6)}`;

  if (!p3) {
    if (p2 === "InRelease" || p2 === "Release.gpg") {
      return serveR2(env, request, r2Key, { ctx });
    }
    if (p2 === "Release") {
      return serveR2(env, request, r2Key, { fetchKey: r2Key.replace("Release", "InRelease"), transform: "strip-pgp", ctx });
    }
  }

  const { components, arches } = distroConfig;

  // Packages & Hashes (dists/debian/.../binary-amd64/...)
  if (p3 && components.has(p2) && p3.startsWith("binary-") && arches.has(p3.slice(7))) {
    if (p4 === "Release") {
      const hbr = new Headers(H_CACHED);
      hbr.set("Content-Type", "text/plain; charset=utf-8");
      hbr.set("X-Debthin", "hit-generated");
      hbr.set("X-Cache", "HIT");
      hbr.set("X-Cache-Hits", "0");
      return new Response(`Archive: ${p1}\nComponent: ${p2}\nArchitecture: ${p3.slice(7)}\n`, { headers: hbr });
    }
    if (p4 === "Packages") {
      return serveR2(env, request, r2Key, { fetchKey: r2Key + ".gz", transform: "decompress" });
    }
    if (p4 === "Packages.gz" || p4 === "Packages.lz4" || p4 === "Packages.xz") {
      return serveR2(env, request, r2Key);
    }
  }

  const byHashIdx = suitePath.indexOf("/by-hash/SHA256/");
  if (byHashIdx !== -1) {
    const sha256 = suitePath.slice(byHashIdx + 16);
    return handleByHash(request, env, ctx, distro, sha256);
  }

  // Not processed natively, redirect to upstream
  return null;
}
